name: GITHUB CICD
on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: node --version
      - run: npm --version
      - name: checkout the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.event.inputs.checkoutRef }}
      - run: npm install
      - run: node app.js
